{{- if not .Values.odoo.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "odoo.secretName" . }}
  labels:
    {{- include "odoo.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.odoo.existingSecretKeys.adminPassword }}: {{ .Values.odoo.config.adminPassword | quote }}
  {{ .Values.odoo.existingSecretKeys.dbPassword }}: {{ .Values.odoo.config.dbPassword | quote }}
{{- end }}
